### ISSUE TITLE
Crash with latest Mystical Agriculture Version

### ISSUE THREAD

**Issue by SanAndreasP** [BlakeBr0/MysticalAgradditions#35]
Forge: 1.12.2-14.23.5.2795
Mystical Agriculture: 1.12.2-1.7.0
Mystical Aggraditions: 1.12-1.2.8

After updating Mystical Agriculture to 1.7.0, it crashes upon load:
```
java.lang.NoClassDefFoundError: com/blakebr0/mysticalagriculture/util/NBTHelper
    at com.blakebr0.mysticalagradditions.items.ItemPaxel.addInformation(ItemPaxel.java:59)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707)
    at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
    at net.minecraft.client.util.SearchTree.index(SourceFile:49)
    at net.minecraft.client.util.SearchTree.add(SourceFile:44)
    at java.lang.Iterable.forEach(Unknown Source)
    ...
```

Logs: https://paste.dimdev.org/povihupexa.mccrash

**Comment by TacticalUniverse** [comment]
Same crash https://paste.dimdev.org/xamoxehuza.mccrash
